package com.example.sxt.command;

import com.example.sxt.SimpleXpTeleportPlugin;
import com.example.sxt.data.dao.HomeDao;
import com.example.sxt.data.model.Home;
import com.example.sxt.message.MessageService;
import com.example.sxt.permission.HomeLimitResolver;
import org.bukkit.entity.Player;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.jetbrains.annotations.NotNull;

import java.util.Map;
import java.util.concurrent.Executor;
import java.util.regex.Pattern;

/**
 * /sethomex [name] — sets a home at the player's current location.
 *
 * <p>Name defaults to {@code "home"} and must match {@code ^[a-zA-Z0-9_\-]{1,32}$}.
 * The per-player limit is resolved by {@link HomeLimitResolver} (honouring
 * {@code sxt.homes.unlimited} / {@code sxt.homes.max.<n>} permissions).
 * Updating an existing home by name does not count against the limit.</p>
 */
public final class SetHomeCommand implements CommandExecutor {

    private static final Pattern NAME_PATTERN = Pattern.compile("^[a-zA-Z0-9_\\-]{1,32}$");

    private final SimpleXpTeleportPlugin plugin;
    private final MessageService msg;
    private final HomeDao homeDao;
    private final HomeLimitResolver homeLimitResolver;
    private final Executor mainThread;

    public SetHomeCommand(SimpleXpTeleportPlugin plugin) {
        this.plugin = plugin;
        this.msg = plugin.getMessageService();
        this.homeDao = plugin.getHomeDao();
        this.homeLimitResolver = new HomeLimitResolver(plugin);
        this.mainThread = task -> plugin.getServer().getScheduler().runTask(plugin, task);
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender,
                             @NotNull Command command,
                             @NotNull String label,
                             @NotNull String[] args) {
        if (!(sender instanceof Player player)) {
            msg.send(sender, "general.player-only", Map.of());
            return true;
        }

        if (args.length > 1) {
            msg.send(sender, "general.usage", Map.of("usage", command.getUsage()));
            return true;
        }

        String homeName = args.length > 0 ? args[0] : "home";

        if (!NAME_PATTERN.matcher(homeName).matches()) {
            msg.send(player, "home.invalid-name", Map.of());
            return true;
        }

        var uuid = player.getUniqueId();

        // Check whether this is a new home or an overwrite
        homeDao.findOne(uuid, homeName).thenAcceptAsync(opt -> {
            if (opt.isPresent()) {
                // Overwriting an existing home — skip limit check
                Home home = buildHome(player, homeName);
                homeDao.save(home).thenAcceptAsync(v ->
                        msg.send(player, "home.set", Map.of("home", homeName)),
                        mainThread);
                return;
            }

            // New home — verify limit
            homeDao.countByPlayer(uuid).thenAcceptAsync(count -> {
                int max = homeLimitResolver.resolve(player);
                if (count >= max) {
                    msg.send(player, "home.limit-reached",
                            Map.of("count", String.valueOf(count),
                                   "max", String.valueOf(max)));
                    return;
                }
                Home home = buildHome(player, homeName);
                homeDao.save(home).thenAcceptAsync(v ->
                        msg.send(player, "home.set", Map.of("home", homeName)),
                        mainThread);
            }, mainThread);

        }, mainThread);

        return true;
    }

    private static Home buildHome(Player player, String name) {
        var loc = player.getLocation();
        long now = System.currentTimeMillis();
        return new Home(
                0L,                     // id (auto-generated by DB)
                player.getUniqueId(),
                name,
                loc.getWorld().getName(),
                loc.getX(), loc.getY(), loc.getZ(),
                loc.getYaw(), loc.getPitch(),
                now,                    // created_at (set on first insert)
                now                     // updated_at
        );
    }
}