package com.example.sxt.command;

import com.example.sxt.SimpleXpTeleportPlugin;
import com.example.sxt.data.dao.WarpDao;
import com.example.sxt.data.model.Warp;
import com.example.sxt.message.MessageService;
import org.bukkit.entity.Player;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.jetbrains.annotations.NotNull;

import java.util.Map;
import java.util.concurrent.Executor;

/**
 * /setwarpx <name> — creates or overwrites a public warp at the player's location.
 *
 * <p>Requires permission {@code sxt.manage.warp}. The warp record is saved
 * via {@link WarpDao#save} on an async thread; the success message is sent
 * back on the main thread.</p>
 */
public final class SetWarpCommand implements CommandExecutor {

    private final SimpleXpTeleportPlugin plugin;
    private final MessageService msg;
    private final WarpDao warpDao;
    private final Executor mainThread;

    public SetWarpCommand(SimpleXpTeleportPlugin plugin) {
        this.plugin = plugin;
        this.msg = plugin.getMessageService();
        this.warpDao = plugin.getWarpDao();
        this.mainThread = task -> plugin.getServer().getScheduler().runTask(plugin, task);
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender,
                             @NotNull Command command,
                             @NotNull String label,
                             @NotNull String[] args) {
        if (!(sender instanceof Player player)) {
            msg.send(sender, "general.player-only", Map.of());
            return true;
        }

        if (!player.hasPermission("sxt.manage.warp")) {
            msg.send(player, "general.no-permission", Map.of());
            return true;
        }

        if (args.length == 0) {
            return false; // show usage
        }

        String warpName = args[0];
        var loc = player.getLocation();
        long now = System.currentTimeMillis();

        Warp warp = new Warp(
                0L,                     // id (auto-generated by DB)
                warpName,
                loc.getWorld().getName(),
                loc.getX(), loc.getY(), loc.getZ(),
                loc.getYaw(), loc.getPitch(),
                player.getUniqueId(),   // created_by
                now,
                now
        );

        warpDao.save(warp).thenAcceptAsync(v ->
                msg.send(player, "warp.set", Map.of("warp", warpName)),
                mainThread);

        return true;
    }
}